baseURL = 'https://headcrash.net/'
defaultContentLanguage = 'de'
title = './HeadCrash'
theme = "headcrash"

disableKinds = ["taxonomy", "term"]

[params]
    logoName = "Logo name"
    email = "dr-hdd@headcrash.net"
    phone = "+49 (0) 30 333 222 333"
    address = [
        "Steindorff Passage",
        "Hauptstraße 2",
        "10405 Berlin",
        "Deutschland",
        "*Parkplätze stehen vor dem Haus zur Verfügung*"
    ]
    
    heroBackground = "59.jpg"


[menu]
    [[menu.info]]
        name = "Kontakt"
        weight = 200
        url = "#"