baseURL = 'https://headcrash.net/'
defaultContentLanguage = 'de'
title = "Datenträgervernichtung, Datenlöschung, Datenrettung — /HeadCrash"

theme = "headcrash"
disableKinds = ["taxonomy", "term"]

[params]
    description = "Datenträgervernichtung, Datenlöschung, Datenrettung"
    logoName = "./HeadCrash"
    email = "dr-hdd@headcrash.net"
    phone = "+49 (0) 30 333 222 333"
    phones = [
        "+49 30 417 25 045",
        "0800-433-5-222"
    ]
    address = [
        "HDDLab / XDatenrettung",
        "Danziger str. 78a",
        "10405 Berlin",
        "Deutschland",
        "*Parkplätze stehen vor dem Haus zur Verfügung*"
    ]
    route = "google map route url"
    
    heroBackground = "59.jpg"

[markup]
  [markup.tableOfContents]
    endLevel = 2