baseURL = 'https://headcrash.net/'
defaultContentLanguage = 'de'
title = "Datenrettung, Datenträgervernichtung, Datenlöschung — ./HeadCrash"

theme = "headcrash"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true

[params]
    description = "Wir sind Ihr führendes Datenrettungsunternehmen für professionelle Datenträgervernichtung, zuverlässige Datenlöschung und effektive Datenwiederherstellung. Vertrauen Sie auf unsere Expertise!"
    name = "HeadCrash"
    logoName = "./HeadCrash"
    foundingDate = 2005
    email = "hddtech@gmx.net"
    phones = [
        "+49 30 417 25 045",
        "0800-433-5-222"
    ]
    address = [
        "*headCrash.net*",
        "Danziger str. 78a",
        "10405",
        "Berlin",
        "Deutschland",
        "*Parkplätze stehen vor dem Haus zur Verfügung*"
    ]
    # "google map route url"
    mapRoute =  "https://www.google.at/maps/dir//Danziger+Str.+78A,+10405+Berlin/@52.5387078,13.4221649,17z/data=!4m18!1m8!3m7!1s0x47a84e0724a8b2b7:0x7ee6cd5e74ad8f56!2sDanziger+Str.+78A,+10405+Berlin!3b1!8m2!3d52.5387046!4d13.4247398!16s%2Fg%2F11csns0kl5!4m8!1m0!1m5!1m1!1s0x47a84e0724a8b2b7:0x7ee6cd5e74ad8f56!2m2!1d13.4247398!2d52.5387046!3e3?hl=de&entry=ttu" 
    
    heroBackground = "59.jpg"

[markup]
  [markup.tableOfContents]
    endLevel = 2