# Do not change!
baseURL = 'https://headcrash.net/'
# Do not change! 
defaultContentLanguage = 'de'
# SEO — text for title tag in head section
title = "Datenrettung, Datenträgervernichtung, Datenlöschung — ./HeadCrash"

# Do not change! Used theme name
theme = "headcrash"
# Do not change!
disableKinds = ["taxonomy", "term"]
# Do not change!
enableRobotsTXT = true

[params]
    # SEO — text for meta description
    description = "Wir sind Ihr führendes Datenrettungsunternehmen für professionelle Datenträgervernichtung, zuverlässige Datenlöschung und effektive Datenwiederherstellung. Vertrauen Sie auf unsere Expertise!"
    # used in the JSON-LD (microdata)
    name = "HeadCrash"
    # used in header
    logoName = "./HeadCrash"
    # used in the JSON-LD and footer
    foundingDate = 2005
    # used in the JSON-LD and footer
    email = "hddtech@gmx.net"
    # Used in the footer
    phones = [
        "030-4408242",
        
    ]
    # Used in the footer
    address = [
        "*headCrash.net*",
        "Siemensstr.10",
        "10551",
        "Berlin",
        "Deutschland",
        "*Parkplätze stehen vor dem Haus zur Verfügung*"
    ]
    # Used in the footer, google map route url
    mapRoute =  "https://www.google.at/maps/dir//Danziger+Str.+78A,+10405+Berlin/@52.5387078,13.4221649,17z/data=!4m18!1m8!3m7!1s0x47a84e0724a8b2b7:0x7ee6cd5e74ad8f56!2sDanziger+Str.+78A,+10405+Berlin!3b1!8m2!3d52.5387046!4d13.4247398!16s%2Fg%2F11csns0kl5!4m8!1m0!1m5!1m1!1s0x47a84e0724a8b2b7:0x7ee6cd5e74ad8f56!2m2!1d13.4247398!2d52.5387046!3e3?hl=de&entry=ttu" 
    
    # Name of the image for the hero section on home page. Image is located ./assets/images/
    heroBackground = "59.jpg"

# Do not change!
[markup]
  [markup.tableOfContents]
    endLevel = 2